### ISSUE TITLE
Page built failed: page.waitForFunction: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by Xuanwo** [pengx17/logseq-publish#28]
The page has been built and failed since today.

They failed for the same reason three times, so I believe it's not a random error.

```shell
Page loaded!
page.waitForFunction: Timeout 30000ms exceeded.
    at loadLocalGraph (file:///home/logseq/publish.mjs:74:14)
    at async main (file:///home/logseq/publish.mjs:206:5) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/www/trace.zip
Export failed
Run actions/upload-artifact@v2
With the provided path, there will be 1 file uploaded
Starting artifact upload
```

The failed actions: https://github.com/Xuanwo/Xuanwo/runs/6021991755?check_suite_focus=true

---

For friends jumps into this issue:

**Quick workaround: use `version: 0.6.5` instead.**

**Comment by pengx17** [comment]
Let me take a look. Seems the new publish script is still broken somehow.

**Comment by Xuanwo** [comment]
I found it hard to debug now:

- We can't specify the version of logseq-publish to use (always use `main`)
- Historic logseq-publish images are not tagged, we have to use image hash instead

**Comment by Xuanwo** [comment]
There are three parts that keep changing...

- build scripts
- build image
- logseq itself

**Comment by pengx17** [comment]
Can you please use Logseq version 0.6.5 for now? This should be mostly stable I suppose.
e.g.,
```yml
      - name: Logseq Publish
        # Using main branch to reproduce https://github.com/pengx17/logseq-publish/issues/8
        # Should switch back to stable release after this issue fixed.
        uses: pengx17/logseq-publish@main
        with:
          version: 0.6.5
          dest: www
```
