### ISSUE TITLE
Enabling export.css

### ISSUE THREAD

**Issue by mklilley** [pengx17/logseq-publish#36]
Hello and thank you so much for making this Github action. I followed your instructions and got some lovely github pages from my Logseq notes.

The one thing I couldn't get to work is `export.css` styles. 

Here is how it is supposed to work:
If you have styles in a file called `export.css` (inside the same folder as `custom.css`) then, when you come to export the graph, logseq uses the styles inside of `export.css` instead of `custom.css`. I've tried this myself using a local desktop app and it works for me. It means I can have custom styles while editing and export styles for exporting.

In my repo, I've committed the `export.css` file but it seems that the Github action isn't picking it up.

Any idea why that might be?

Thanks

PS. here is my workflow.

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
        with:
          version: master
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
```

**Comment by pengx17** [comment]
The reason is because by default the Logseq version (when you specify `version: master` in the pengx17/logseq-publish field) being used in this action is outdated and does not support `export.css` which is introduced in a later version.
In the mean time, if you would want to use the action to publish your graph, you can move the contents of export.css to custom.css, which should work normally.
I would like to update the Logseq version sometime in the near future, but I cannot make a promise if I have the time though 😅

**Comment by mklilley** [comment]
Thanks for getting back to me @pengx17 . After doing a bit of digging I also realised export was a recent thing. I completely appreciate that you might not have time to update the Action and I want to thank you again for making this version - it's great.

If you have a little time (or anyone else who sees this) I'd appreciate your thoughts on what goes wrong when one tries to use the action with Logseq version 0.7.1. In other words, what goes wrong when you set the workflow yaml file to have:
```
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
        with:
          version: 0.7.1
```

I tried it this morning and it doesn't work but can't quite see an obvious reason why.

I checked out the playwright trace using https://trace.playwright.dev/ as you advised (trace zip available here https://github.com/mklilley/Bhatia/blob/gh-pages/trace.zip) and everything seems to go fine. It just seems to hang. The hanging is consistent with the logs which say `export timeout`

![Screenshot 2022-07-10 at 09 42 22](https://user-images.githubusercontent.com/7937044/178138059-6dbe05b8-e851-478d-b570-588001d9806a.png)

It does seem to be trying to `checkGraphDistPathExist` a lot. I took a look at `publish.mjs` to have a little geek out. Presumably it's failing because this line https://github.com/pengx17/logseq-publish/blob/main/publish.mjs#L87 is always evaluating to false? i.e.:

```
      if (
        distPathExists ||
        (graphDistPath &&
          fs.statSync(path.join(graphDistPath, "static")).isDirectory())
      )
```

Is it obvious why that would be the case? Happy to do some more digging myself.... i just don't want to go on a wild goose chase.
