### ISSUE TITLE
Export failed in action

### ISSUE THREAD

**Issue by fortunehan** [pengx17/logseq-publish#45]
Hi @pengx17 ,

May I seek your help to check an error?

I am trying the action to publish public notes, but got below error.
Seems the "export graph" button cannot be click.
Below is part of action log.

```
Graph loaded for /home/logseq/graph
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "a.menu-link >> text=Export graph"
  selector resolved to visible <div>Export graph</div>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not stable - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="text-sm leading-5 font-medium whitespace-…>Page already exists with another file: /home/logs…</div> from <div class="notifications ui__notifications">…</div> subtree intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="text-sm leading-5 font-medium whitespace-…>Page already exists with another file: /home/logs…</div> from <div class="notifications ui__notifications">…</div> subtree intercepts pointer events

...

retrying click action, attempt #50
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="text-sm leading-5 font-medium whitespace-…>Page already exists with another file: /home/logs…</div> from <div class="notifications ui__notifications">…</div> subtree intercepts pointer events
retrying click action, attempt #51
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="text-sm leading-5 font-medium whitespace-…>Page already exists with another file: /home/logs…</div> from <div class="notifications ui__notifications">…</div> subtree intercepts pointer events
retrying click action, attempt #52
  waiting 500ms
============================================================
    at publish (file:///home/logseq/publish.mjs:111:14)
    at async main (file:///home/logseq/publish.mjs:193:5) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/www/trace.zip
Export failed
```

Below is my workflow yml
``` yaml
# This is a basic workflow to help you get started with Actions

name: Publish Public Notes

# Controls when the workflow will run
on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@v0.1
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          single-commit: true
```
