### ISSUE TITLE
How to publish with specific release of Logseq？

### ISSUE THREAD

**Issue by WsinGithub** [pengx17/logseq-publish#48]
When publishing, latest releases of Logseq often have bugs.

So if it is possible to publish with the release I want, such as 0.7.5 which is used now on my Desktop.

---
新版本发布时或多或少有 bug，请问如何选择特定版本进行发布呢？

譬如打算未来长期使用 0.7.5 作为发布版本。

:D

**Comment by WsinGithub** [comment]
0.8.8 没法折叠，0.8.9 直接把 https://logseq.pro/ 的主页搞炸了 😢

https://github.com/logseq/logseq/issues/7118

**Comment by pengx17** [comment]
The publish docker image is built manually and there are only a few of them, which can be found in https://github.com/pengx17/logseq-publish/pkgs/container/logseq-publish/versions. Note you can ignore the long hashed versions.
To use a specific version,  use the following:

```
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
        with:
          version: "0.7.6"
```
