### ISSUE TITLE
Make logseq-publish-for-gitlab!

### ISSUE THREAD

**Issue by gwpl** [pengx17/logseq-publish#55]
Feature request: could you make logseq-publish-for-gitlab?

One may like to use https://docs.gitlab.com/ee/user/project/pages/ gitlab pages,
therefore gitlab runner https://docs.gitlab.com/runner/ 
for fluent CI/CD experience https://docs.gitlab.com/ee/ci/

**Comment by gwpl** [comment]
Maybe this would be helpful:
https://tomasvotruba.com/blog/how-can-we-use-github-actions-in-gitlab/

**Comment by Xuanwo** [comment]
Gitlab support should live in another project (maybe in gitlab directly so easier for test and adopt). Since `logseq-publish` is licensed under MIT, It's OK for you to fork one to gitlab~

**Comment by MarkusPic** [comment]
Hi,

this is what worked for me on gitlab:

First you have to enable pages. (https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ui.html)

Also I used a scheduled pipeline. (https://docs.gitlab.com/ee/ci/pipelines/schedules.html)

This is my `.gitlab-ci-yml`:

```yaml
pages:
  image: ghcr.io/pengx17/logseq-base:master
  stage: deploy
  script:
    - mkdir public
    - mv publish.mjs /home/logseq/publish.mjs
    - cd /home/logseq
    - "xvfb-run node /home/logseq/publish.mjs -p $CI_PROJECT_DIR -t $CI_PROJECT_DIR/public/build_trace.txt -o $CI_PROJECT_DIR/public"
  artifacts:
    paths:
      - public
  only:
    - schedules
```

My git repository has the following structure:
```
assets/
journals/
logseq/
pages/
.gitlab-ci-yml
publish.mjs
```
