### ISSUE TITLE
The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌ Deployment failed!

### ISSUE THREAD

**Issue by yorkjong** [pengx17/logseq-publish#61]
I got the error on Deploy phase.

The error message is as follows:

Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by yorkjong** [comment]
Problem solved by using github-pages-deploy-action@v4 as follows:

```yml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
```
